version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export ACCOUNT_ID=$(cat account_id.txt)
      - export REPOSITORY_NAME=$(cat ecr_name.txt)
      - export REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - echo $REPOSITORY_URI
      - echo $ACCOUNT_ID
      - echo $AWS_DEFAULT_REGION
      - echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - '**/*'
  discard-paths: yes